swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "RSO Directory API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3081"
tags:
- name: "rso"
  description: "Everything about RSO information"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /rsos:
    get:
      tags:
      - "rso"
      summary: "Gets 20 rsos"
      description: ""
      operationId: "rsos"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
  /rsos/search:
    get:
      tags:
      - "rso"
      summary: "Searches for RSOs matching given query"
      description: ""
      operationId: "searchRso"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: query
          schema:
            type: String
          required: true
          description: term to search for
  /rsos/category:
    get:
      tags:
      - "rso"
      summary: "Gets RSOs matching the given category"
      description: "todo: accept multiple categories"
      operationId: "categoryRso"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: category
          schema:
            type: String
          required: true
          description: "category of the RSOs to return. Valid categories found through rsos/allcategories"
  /rsos/allcategories:
    get:
      tags:
        - "rso"
      summary: "Gets a list of all valid categories"
      description: "gets a list of categories that can be used for /rsos/category"
      operationId: "allCategories"
      produces:
      - "application/json"
